class Vector2:
    x: float
    y: float

    def __init__(self, x: float = 0.0, y: float = 0.0) -> None: ...
    def __add__(self, other: 'Vector2') -> 'Vector2': ...
    def __sub__(self, other: 'Vector2') -> 'Vector2': ...
    def __mul__(self, scalar: float) -> 'Vector2': ...
    def length(self) -> float: ...
    def normalized(self) -> 'Vector2': ...
    def normalize(self) -> None: ...