class Vector2:
    x: float
    y: float

    def __init__(self, x: float = 0.0, y: float = 0.0) -> None: ...
    def __add__(self, other: 'Vector2') -> 'Vector2': ...
    def __sub__(self, other: 'Vector2') -> 'Vector2': ...
    def __mul__(self, scalar: float) -> 'Vector2': ...
    def __truediv__(self, scalar: float) -> 'Vector2': ...
    def __repr__(self) -> str: ...
    def length(self) -> float: ...
    def lengthSquared(self) -> float: ...
    def dot(self, other: 'Vector2') -> float: ...
    def distanceTo(self, other: 'Vector2') -> float: ...
    def distanceSquaredTo(self, other: 'Vector2') -> float: ...
    def normalized(self) -> 'Vector2': ...
    def normalize(self) -> 'Vector2': ...
